build:
    tests:
        override:
            -
                command: phpunit --coverage-clover=my-coverage-file --coverage-text test.php
                coverage:
                    file: my-coverage-file
                    format: php-clover
    environment:
        php:
            version: 5.5.12
checks:
    php:
        code_rating: true
        code_metrics: true
        duplication: true
