language: php
script: phpunit --testdox-text=testdox --coverage-clover=coverage.clover --coverage-text test.php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  - hhvm-nightly
after_script:
  - less textdox
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
